### ISSUE TITLE
[FEATURE REQUEST] Implement NumericNonOverflowingMod in Interval domain

### ISSUE THREAD

**Issue by simonegazza** [lisa-analyzer/lisa#216]
**Description**
It seems that `NumericNonOverflowingMod` always returns top when using the interval domain.

**Motivation**
This kind of operator in particular is also used in [rust-lisa](https://github.com/lisa-analyzer/rust-lisa); also further expansion of arithmetic operations should improve some analysis.

**Comment by VincenzoArceri** [comment]
Instead of returning `TOP`, we could return the interval `[0, +Inf]`.
